apiVersion: skaffold/v4beta9
kind: Config
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: skaffold
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          LD_FLAGS: ""
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - skaffold
