apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-dcd-controller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: controller
          image: skaffold
          imagePullPolicy: Always
          args:
            - --metrics-addr=0.0.0.0:8080
            - --enable-leader-election
            - --verbose
          env:
            - name: VARIANT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['variant']
          volumeMounts:
            # delve uses /home/nonroot/.config for storing delve configuration
            - name: tmp
              mountPath: /home/nonroot/.config
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
