name: PullRequest
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.22.6
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.6
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint
        run: make lint
